# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-21.10"
  config.vm.hostname = "vault.local"
  config.vm.box_check_update = false

  config.vm.network "private_network", ip: "192.168.56.8"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "512"
	 vb.linked_clone = true
  end
end
